{% set name = "methodtools" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e213439dd64cfe60213f7015da6efe5dd4003fd89376db3baa09fe13ec2bb0ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - wirerope >=0.4.7

test:
  imports:
    - methodtools
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/youknowone/methodtools
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Expand standard functools to methods
  doc_url: https://methodtools.readthedocs.io/en/latest/
  dev_url: https://github.com/youknowone/methodtools

extra:
  recipe-maintainers:
    - timkpaine
